@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

AddressBook *-right-> "1" UniquePatientList

UniquePatientList -right-> Patient

Patient --> "*" Tag

Patient *--=> "*" Medicine
Patient *--> Name
Patient *--> Phone
Patient *--> Email
Patient *--> Address
Patient *--> LastVisit
@enduml
