@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":UnprescribeCommandParser" as UnprescribeParser LOGIC_COLOR
participant "u:UnprescribeCommand" as UnprescribeCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box
[-> LogicManager : execute("unprescribe 1 m/Paracetamol")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("unprescribe 1 m/Paracetamol")
activate AddressBookParser

create UnprescribeParser
AddressBookParser -> UnprescribeParser
activate UnprescribeParser

UnprescribeParser --> AddressBookParser
deactivate UnprescribeParser

AddressBookParser -> UnprescribeParser : parse("1 m/Paracetamol")
activate UnprescribeParser

create UnprescribeCommand
UnprescribeParser -> UnprescribeCommand : new UnprescribeCommand(index, medicine)
activate UnprescribeCommand

UnprescribeCommand --> UnprescribeParser
deactivate UnprescribeCommand

UnprescribeParser --> AddressBookParser : u
deactivate UnprescribeParser

AddressBookParser --> LogicManager : u
deactivate AddressBookParser

LogicManager -> UnprescribeCommand : execute()
activate UnprescribeCommand

UnprescribeCommand -> Model : getFilteredPatientList()
activate Model
Model --> UnprescribeCommand : patientList
deactivate Model

UnprescribeCommand -> Model : setPatient(patientToEdit, editedPatient)
activate Model
Model --> UnprescribeCommand
deactivate Model

UnprescribeCommand -> Model : updateFilteredPatientList()
activate Model
Model --> UnprescribeCommand
deactivate Model

UnprescribeCommand --> LogicManager : result
deactivate UnprescribeCommand
UnprescribeCommand -[hidden]-> LogicManager : result
destroy UnprescribeCommand

[<--LogicManager
deactivate LogicManager
@enduml
